
- name: Install Dependencies
  hosts: all
  tasks:
   - name: Install Curl2
     yum:
      name: curl
      state: latest

   - name: Install Pip
     yum:
      name: python-pip
      state: latest

   - name: Install Python Requests
     pip:
      name: requests
      state: present

   - name: Install Artifactory
     QSArtifactory:
      build_id: "{{BuildID}}"
      artifactory_ip: "{{ArtifactoryIP}}"
      artifactory_username: "{{ArtifactoryUsername}}"
      artifactory_password: "{{ArtifactoryPassword}}"
      file_name: "{{FileName}}"
      artifact_repo: "{{ArtifactoryRepo}}"
      xray_ip: "{{XrayIP}}"
      xray_username: "{{XrayUsername}}"
      xray_password: "{{XrayPassword}}"